_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": darwin-arm64
command_cfg:
    value:
        ang_vel_range:
            - 0
            - 0
        lin_vel_x_range:
            - 0.1
            - 0.4
        lin_vel_y_range:
            - 0
            - 0
        num_commands: 3
device:
    value: mps
env_cfg:
    value:
        action_scale: 0.25
        base_init_pos:
            - 0
            - 0
            - 0.41
        base_init_quat:
            - 1
            - 0
            - 0
            - 0
        clip_actions: 100
        default_joint_angles:
            L_Ankle_Pitch: 0
            L_Hip_Pitch: 0
            L_Hip_Roll: 0
            L_Hip_Yaw: 0
            L_Knee_Pitch: 0
            R_Ankle_Pitch: 0
            R_Hip_Pitch: 0
            R_Hip_Roll: 0
            R_Hip_Yaw: 0
            R_Knee_Pitch: 0
        dof_names:
            - R_Hip_Pitch
            - L_Hip_Pitch
            - R_Hip_Yaw
            - L_Hip_Yaw
            - R_Hip_Roll
            - L_Hip_Roll
            - R_Knee_Pitch
            - L_Knee_Pitch
            - R_Ankle_Pitch
            - L_Ankle_Pitch
        episode_length_s: 20
        kd: 0.5
        kp: 20
        num_actions: 10
        resampling_time_s: 4
        simulate_action_latency: true
        termination_if_pitch_greater_than: 10
        termination_if_roll_greater_than: 10
max_iterations:
    value: 10
num_envs:
    value: 8912
obs_cfg:
    value:
        num_obs: 39
        obs_scales:
            ang_vel: 0.25
            dof_pos: 1
            dof_vel: 0.05
            lin_vel: 2
reward_cfg:
    value:
        base_height_target: 0.3
        feet_height_target: 0.075
        reward_scales:
            action_rate: -0.0001
            base_height: -1
            lin_vel_z: -0.02
            similar_to_default: -0.002
            tracking_ang_vel: 0.004
            tracking_lin_vel: 0.02
        tracking_sigma: 0.25
show_viewer:
    value: false
